[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["UniversalFactory"]

########
# Lint #
########
deny_warnings = true

################
# Solc options #
################
solc = '0.8.27'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200000
via_ir = true

#####################
# optimizer details #
#####################
[profile.default.optimizer_details]
yul = true
# The peephole optimizer is always on if no details are given,
# use details to switch it off.
peephole = true
# The inliner is always off if no details are given,
# use details to switch it on.
inliner = true
# The unused jumpdest remover is always on if no details are given,
# use details to switch it off.
jumpdest_remover = true
# Sometimes re-orders literals in commutative operations.
order_literals = true
# Removes duplicate code blocks
deduplicate = false
# Common subexpression elimination, this is the most complicated step but
# can also provide the largest gain.
cse = true
# Optimize representation of literal numbers and strings in code.
constant_optimizer = true
# Use unchecked arithmetic when incrementing the counter of for loops
# under certain circumstances. It is always on if no details are given.
simple_counter_for_loop_unchecked_increment = true

###############
# EVM options #
###############
gas_limit = 30000000
gas_price = 1
block_base_fee_per_gas = 0
block_gas_limit = 30000000

######################
# Fuzz tests options #
######################
[fuzz]
# Reduce the numbers of runs if fuzz tests takes too long in your machine.
runs = 2500

# When debuging fuzz tests, uncomment this seed to make tests reproducible.
# seed = "0xdeadbeefdeadbeefdeadbeefdeadbeef"

# RPC endpoints
[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/pwc5rmJhrdoaSEfimoKEmsvOjKSmPDrP"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
holesky = "https://rpc.holesky.ethpandaops.io"
astar = "https://evm.astar.network"
astar_shiden = "https://evm.shiden.astar.network"
astar_shibuya = "https://evm.shibuya.astar.network"
polygon = "https://polygon-rpc.com"
polygon_amoy = "https://rpc-amoy.polygon.technology"
optimism = "https://sepolia.optimism.io"
optimism_sepolia = "https://sepolia.optimism.io"
arbitrum_one = "https://arb1.arbitrum.io/rpc"
arbitrum_one_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc"
bnb_smart_chain = "https://bsc-dataseed1.binance.org"
bnb_smart_chain_testnet = "https://rpc.ankr.com/bsc_testnet_chapel"
gnosis_chain = "https://rpc.gnosischain.com"
moonbeam = "https://rpc.api.moonbeam.network"
moonriver = "https://rpc.api.moonriver.moonbeam.network"
moonbase = "https://rpc.testnet.moonbeam.network"
